/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.smarttasks;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainActivityTest {
    @Test 
    public void testMainActivityExists() {
        // Basic test to ensure MainActivity class can be instantiated
        assertNotNull("MainActivity class should exist", MainActivity.class);
    }
}
